### ISSUE TITLE
Ledger issues tracking

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#103]
### Ledger device: CLA_NOT_SUPPORTED (0x6e00)
Device: Ledger Nano S Plus
App: v0.5.5
Error: failed to get firmware version, 
Issue: https://github.com/LedgerHQ/ledger-live/issues/2583
Status: [Resolved](https://github.com/LedgerHQ/ledger-live/issues/2583#issuecomment-1442544299)
Response: As the logs explain, `CLA_NOT_SUPPORTED` or `INS_NOT_SUPPORTED` mean that you are sending a message that the current application can't handle. Some APDU messages such as `b001000000` will work regardless of the app running and will give you information about the current app running on the device. Depending on what you are trying to do, perhaps we can help better [on Discord](https://developers.ledger.com/contact/) for development.

### Ledger device: UNKNOWN_ERROR(0x6e01)
Device: Ledger Nano X
App: v0.5.5
Error: TransportStatusError
Issue: https://github.com/nervosnetwork/neuron/pull/2581#issuecomment-1423532722
Status: Resolved
Response: Fixed by keeping ledger open during operation

### cannot open device with path
Device: Ledger Nano X
App: v0.5.5
Error: Error: cannot open device with path, Neuron hangs on confirming a signing action
Issue: https://github.com/nervosnetwork/neuron/issues/2583
Status: [Resolved](https://github.com/nervosnetwork/neuron/issues/2583#issuecomment-1474741141)
Response: Fixed by upgrading ledger ckb app to v0.5.6

### Ledger device: UNKNOWN_ERROR (0x9405)
Device: Ledger Nano X
App: v0.5.5
Error: Ledger device: UNKNOWN_ERROR (0x9405), failed to sign a transaction
Issue: reported from an e-mail
Status: debugging

**Comment by homura** [comment]
The same error code in https://github.com/nervosnetwork/neuron/issues/3095

**Comment by homura** [comment]
The error code [0x9405](https://github.com/LedgerHQ/app-nervos/blob/02b32f2d9932f004b21fb4925b7c57347cb2d7d8/src/exception.h#L16) was thrown from the Ledger Nervos App.

This error occurs in the following situations:

1. The transaction sent to the Ledger device is incompleted https://github.com/homura/app-nervos/blob/327098db14e1972fe5941eaa67c5ce0d56e2ee24/src/apdu_sign.c#L1000-L1015
2. Too many packets sent to the Ledger device https://github.com/homura/app-nervos/blob/327098db14e1972fe5941eaa67c5ce0d56e2ee24/src/apdu_sign.c#L1180-L1185
3. An unexpected magic byte is encountered https://github.com/homura/app-nervos/blob/327098db14e1972fe5941eaa67c5ce0d56e2ee24/src/apdu_sign.c#L1191 https://github.com/homura/app-nervos/blob/327098db14e1972fe5941eaa67c5ce0d56e2ee24/src/apdu_sign.c#L1119
4. An unexpected hash size is encountered when signing a message digest https://github.com/homura/app-nervos/blob/327098db14e1972fe5941eaa67c5ce0d56e2ee24/src/apdu_sign.c#L1276

It is recommended to address these specific situations instead of using the generic error code 0x9405

**Comment by homura** [comment]
After reviewing the source code of several Ledger Apps, including [app-bitcoin](https://github.com/LedgerHQ/app-bitcoin-new/blob/develop/src/boilerplate/sw.h), [app-ethereum](https://github.com/LedgerHQ/app-ethereum/blob/4eb5ed3a194670f003e1f7aa23e90d6d727b77af/src/apdu_constants.h), and others, I noticed that these apps use error codes mostly from the APDU protocol's error [code list](https://www.eftlab.com/knowledge-base/complete-list-of-apdu-responses) instead of providing a detailed error code list. This seems to be a common pattern for developing a Ledger app
