### ISSUE TITLE
Change `localhost` to `127.0.0.1`.

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#122]
After `Electron`'s update to 23, its internal node's version becomes 18.12.1, so we need to change `localhost` to `127.0.0.1`.

**Comment by WhiteMinds** [comment]
After considering, it is indeed necessary to directly modify the default value of `rpc_url` to `127.0.0.1`, instead of using the `dns.setDefaultResultOrder(ipv4)` solution. The remaining issue is, how to handle old data?

One option is to replace the host with `127.0.0.1` in `readConfig` when the name is `default node` and the host is `localhost`.
However, other nodes added by users may also have referred to the default configuration and used `localhost`, so it might be necessary to replace all of them, while considering the possibility that users might have intentionally used `localhost`.

There are two solutions:

1. Add a version number to the configuration file, such as `ver: 1`, and then perform operations similar to database schema migration based on the version number.
2. By default, replace all 'localhost' instances in the rpc_url configuration with 127.0.0.1. When users indeed want to use ipv6, they need to explicitly configure `::1` instead of `localhost`.

I plan to use Solution 2, as it involves less complexity and leaves open the possibility of upgrading to Solution 1 in the future.

**Comment by Keith-CY** [comment]
> After considering, it is indeed necessary to directly modify the default value of `rpc_url` to `127.0.0.1`, instead of using the `dns.setDefaultResultOrder(ipv4)` solution. The remaining issue is, how to handle old data?
> 
> One option is to replace the host with `127.0.0.1` in `readConfig` when the name is `default node` and the host is `localhost`. However, other nodes added by users may also have referred to the default configuration and used `localhost`, so it might be necessary to replace all of them, while considering the possibility that users might have intentionally used `localhost`.
> 
> There are two solutions:
> 
> 1. Add a version number to the configuration file, such as `ver: 1`, and then perform operations similar to database schema migration based on the version number.
> 2. By default, replace all `localhost` instances in the `rpc_url` configuration with `127.0.0.1`. When users indeed want to use ipv6, they need to explicitly configure `::1` instead of `localhost`.
> 
> I plan to use Solution 2, as it involves less complexity and leaves open the possibility of upgrading to Solution 1 in the future.

**Solution 2** + 1.
Local nodes can be assumed to be at ipv4 until ckb node uses ipv6 by default.

**Comment by yanguoyu** [comment]
Solution 2 is better, it will not need to consider migrating the old settings. And it is also compatible with ipv4 if the user adds a network with ipv4.

**Comment by WhiteMinds** [comment]
> Solution 2 + 1.

If solution 1 is used, there is no need to use solution 2. Therefore, I think using solution 2 here is sufficient.
Solution 1 will increase the complexity, so if it is not necessary at the moment, it is better not to use it, as there may be other changes in the project structure in the future.

**Comment by Keith-CY** [comment]
> After considering, it is indeed necessary to directly modify the default value of `rpc_url` to `127.0.0.1`, instead of using the `dns.setDefaultResultOrder(ipv4)` solution. The remaining issue is, how to handle old data?
> 
> One option is to replace the host with `127.0.0.1` in `readConfig` when the name is `default node` and the host is `localhost`. However, other nodes added by users may also have referred to the default configuration and used `localhost`, so it might be necessary to replace all of them, while considering the possibility that users might have intentionally used `localhost`.
> 
> There are two solutions:
> 
> 1. Add a version number to the configuration file, such as `ver: 1`, and then perform operations similar to database schema migration based on the version number.
> 2. By default, replace all `localhost` instances in the `rpc_url` configuration with `127.0.0.1`. When users indeed want to use ipv6, they need to explicitly configure `::1` instead of `localhost`.
> 
> I plan to use Solution 2, as it involves less complexity and leaves open the possibility of upgrading to Solution 1 in the future.

The reason `modify the default value` over `using dns.setDefaultResultOrder(ipv4)` is missing

**Comment by WhiteMinds** [comment]
> The reason `modify the default value` over `using dns.setDefaultResultOrder(ipv4)` is missing

Oh, let me add to that.

If we use this API, it is highly likely to become a technical debt because it may affect other DNS resolutions, which may lead us to make decisions to write other code with a bias towards using IPv4, while the future should embrace IPv6.

While other solutions may also become a technical debt, the cost of cleaning them up is very low.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2652/files#diff-cd48aaf82ea7f3fdfea4a4bbacc52194bb694fc96a1b5dfc642f098bbc1b10c9R187-R199 will add `/` at the end of the URL, so it will not equal `BUNDLED_CKB_URL` after replace `localhost` to `127.0.0.1`, and then it can't start internal ckb node.
And same as `BUNDLED_LIGHT_CKB_URL`.

**Comment by WhiteMinds** [comment]
> https://github.com/nervosnetwork/neuron/pull/2652/files#diff-cd48aaf82ea7f3fdfea4a4bbacc52194bb694fc96a1b5dfc642f098bbc1b10c9R187-R199 will add `/` at the end of the URL, so it will not equal `BUNDLED_CKB_URL` after replace `localhost` to `127.0.0.1`, and then it can't start internal ckb node. And same as `BUNDLED_LIGHT_CKB_URL`.

Fixed in https://github.com/nervosnetwork/neuron/pull/2655.
