### ISSUE TITLE
Replace neuron/packages/ckb-indexer with lumos/ckb-indexer

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#140]
Neuron has its own [ckb-indexer] module forked from lumos/ckb-indexer because lumos was not maintained and had compatible issues of hardfork at that time.

Now lumos is referenced as the recommended SDK and actively maintained so that the forked one can be removed for maintenance.
 
Ref: 
- neuron/packages/ckb-indexer: https://github.com/nervosnetwork/neuron/tree/develop/packages/ckb-indexer
- lumos/packages/ckb-indexer: https://github.com/ckb-js/lumos/tree/develop/packages/ckb-indexer

**Comment by homura** [comment]
Lumos is refactoring a new [`Indexer`](https://github.com/ckb-js/lumos/pull/503) that makes [chained-transaction](https://talk.nervos.org/t/non-blocking-chained-transaction-and-its-applications-in-ckb/6649) easy. To use a not quite correct but well understood analogy, this means that we are able to use a cell more than one times in a block. Are we considering integrating this new `Indexer`? Or should just refactor the existing indexer?

**Comment by Keith-CY** [comment]
> Lumos is refactoring a new [`Indexer`](https://github.com/ckb-js/lumos/pull/503) that makes [chained-transaction](https://talk.nervos.org/t/non-blocking-chained-transaction-and-its-applications-in-ckb/6649) easy. To use a not quite correct but well understood analogy, this means that we are able to use a cell more than one times in a block. Are we considering integrating this new `Indexer`? Or should just refactor the existing indexer?

Does it require much work to upgrade the existing indexer to the chained one?

`Chained-transactions` is not so desired for a wallet, and the PRD should be updated for this new feature, which means @Danie0918 and @Sven-TBD should have a view of this function.

**Comment by homura** [comment]
I replaced the indexer to the `lumos/ckb-indexer@0.20`, but I find that Neuron still using `lumos@0.18` as dependency, so I'm trying to upgrade lumos to 0.20 together, but I can't change all the code to camel case directly through [codemod](https://lumos-website.vercel.app/migrations/migrate-to-v0.19#step-1---codemod) because some libraries like Ledger still use the snake case data structure

**Comment by homura** [comment]
It is better to enable the [explicit-function-return-type](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) to avoid uncertain return values cause unexpected breaking change when refactoring or upgrading

![image](https://github.com/Magickbase/neuron-public-issues/assets/7511174/9b33a25f-4013-4e72-bac1-7a80bb2ee985)

**Comment by homura** [comment]
It is better to enable the [no-explicit-any](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md) to avoid using `any` everywhere that makes refactor so hard

**Comment by homura** [comment]
inconsistent asynchronous processing which mixed "async" and "rxjs", makes it harder to maintain

**Comment by yanguoyu** [comment]
> It is better to enable the [no-explicit-any](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md) to avoid using `any` everywhere that makes refactor so hard

This is a previous technical debt, and we are trying to refactor it. https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/.eslintrc.js#L21-L22. You can try to avoid using any when refactoring.

**Comment by yanguoyu** [comment]
> It is better to enable the [explicit-function-return-type](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) to avoid uncertain return values cause unexpected breaking change when refactoring or upgrading
> 
> ![image](https://user-images.githubusercontent.com/7511174/240509224-9b33a25f-4013-4e72-bac1-7a80bb2ee985.png)

The type can be inferenced by return. Do you mean we should avoid using unknown type for return type?

**Comment by homura** [comment]
> The type can be inferenced by return. Do you mean we should avoid using unknown type for return type?

Although TypeScript is able to derive some values automatically, sometimes what is derived is not what we expect, for example, in the above example, `getLiveCellsByScript` returns a `Promise<unknown>`, but if we explicitly mark the return value as `Promise<Cell[]>`, the `unknown` will not be allowed at compile time. When refactoring, there are many errors that can be checked at compile time, rather than running up a test case, finding the error in runtime, and then fixing it

**Comment by yanguoyu** [comment]
> inconsistent asynchronous processing which mixed "async" and "rxjs", makes it harder to maintain

IMO, `async` and `rxjs` are used to resolve different problems. By the way, do you have some suggestions?

**Comment by homura** [comment]
> IMO, `async` and `rxjs` are used to resolve different problems. By the way, do you have some suggestions?

For example, I find the most use case in Neuron is the "queue" to limit the concurrency, "rxjs" also provided some useful operator to handle this, e.g. `mergeMap`

Also, instead of executing tasks [one by one in a queue](https://github.com/nervosnetwork/neuron/blob/4b6868f5ee1c01ed5d6fbe6fc18cb440204d8ac9/packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts#L180), we can even easily do chunk + batch operations on tasks by scheduling them with rxjs, which allows for efficient performance improvements and simple code


```ts
lastValueFrom(
  from(txHashes).pipe(
    bufferCount(100), // make chunks
    mergeMap((txHashes) => batchRequest(txHashes) ,1)
  )
)
```

**Comment by yanguoyu** [comment]
> > IMO, `async` and `rxjs` are used to resolve different problems. By the way, do you have some suggestions?
> 
> For example, I find the most use case in Neuron is the "queue" to limit the concurrency, "rxjs" also provided some useful operator to handle this, e.g. `mergeMap`
> 
> Also, instead of executing tasks [one by one in a queue](https://github.com/nervosnetwork/neuron/blob/4b6868f5ee1c01ed5d6fbe6fc18cb440204d8ac9/packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts#L180), we can even easily do chunk + batch operations on tasks by scheduling them with rxjs, which allows for efficient performance improvements and simple code
> 
> ```ts
> lastValueFrom(
>   from(txHashes).pipe(
>     bufferCount(100), // make chunks
>     mergeMap((txHashes) => batchRequest(txHashes) ,1)
>   )
> )
> ```

Gotcha, I mistakenly thought that `async` is `async await`. I think it's a good idea to replace `async` library with `rxjs`.

**Comment by homura** [comment]
https://github.com/nervosnetwork/neuron/pull/2683
