### ISSUE TITLE
Loading/sync icons lack animation

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#161]
The two arrows in the screenshot are synchronous marks, which require dynamic effects.
Blocks or CKB are dynamically displayed when synchronization is required, and hidden when synchronization is not required.

<img width="984" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/5ad75afd-0e93-423b-8295-240650ac2e6a">

**Comment by FrederLu** [comment]
@Kirl70 
It is necessary to provide a dynamic effect of the loading/synchronizing icon.

**Comment by Kirl70** [comment]
icons gif:
[Loading:sync icons.zip](https://github.com/Magickbase/neuron-public-issues/files/11576567/Loading.sync.icons.zip)



Because the icons in the design draft have a size of only 10px, it is uncertain whether the exported GIF will function properly. If it doesn't, please ask the developer to use this example for production: rotate 360 degrees, with one complete rotation taking 2 seconds, and loop the animation.

![loading icon](https://github.com/Magickbase/neuron-public-issues/assets/106060898/10bf2c66-5a48-4055-bb19-87b3150344ba)

**Comment by yanguoyu** [comment]
Ok, We can achieve this through CSS animation.

**Comment by JeffreyMa597** [comment]
PR:https://github.com/nervosnetwork/neuron/pull/2698

**Comment by FrederLu** [comment]
Verified.
