### ISSUE TITLE
Add a new method of PRC to trigger address generation

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#180]
This PRC is a complement to namespaces for wallet connect(https://github.com/Magickbase/neuron-public-issues/issues/148)

Unlike an account of ETH, an account of CKB would have infinite addresses, and the count of addresses grows along with sending/receiving transactions actively.

In some cases, especially when the wallet is offline, the addresses won't be derived automatically because it cannot sync on-chain data to detect address consumption. Then providing a method to trigger address generation is inevitable.

This issue proposes the draft to allow wallet authorize dapps to generate addresses.

1. a new field named `allow_address_generation: Array<lock type>` will be allowed in authorization;
2. a PRC named `generate_address(args: Array<lock type>): Array<count>` will be supported to inform the wallet to generate specified addresses. The count of addresses to generate is defined inside the wallet, the same as it drives addresses actively.

**Comment by yanguoyu** [comment]
IMO, it is necessary to add this method.
And the suggestion from @homura is good, we can limit derived addresses when the Neuron works with node.
And we can give the control to users over whether DApps can derive addresses.

**Comment by Keith-CY** [comment]
> IMO, it is necessary to add this method. And the suggestion from @homura is good, we can limit derived addresses when the Neuron works with node. And we can give the control to users over whether DApps can derive addresses.

Sure, I would suggest the following strategies:

1. Expose `generate_address` if the wallet is a cold wallet so it can derive its address by an external incentive;
2. Enclose `generate_address` once the wallet is not cold anymore because `cold wallet => hot wallet` is unidirectional.

With these two rules, the address derivation can be guaranteed and will not be abused by DApp.

Along with this feature, a field named `is_cold_wallet` may be necessary when the wallet is exported/imported to inform the wallet how to adopt the strategy.

**Comment by homura** [comment]
IMO, the address should only be derived by the wallet, since it is a risky operation, it may cause assets to be hard, or even impossible to be recovered.

I don't think we need to consider the address derivation RPC for a cold wallet. Or, when Neuron is used as a cold wallet, there should be another protocol to interact with, like Ledger's [Ledger Live](https://support.ledger.com/hc/en-us/articles/8979990022045-How-to-connect-to-NEAR-Wallet-with-your-Ledger-device?docs=true)

**Comment by Keith-CY** [comment]
> IMO, the address should only be derived by the wallet, since it is a risky operation, it may cause assets to be hard, or even impossible to be recovered.
> 
> I don't think we need to consider the address derivation RPC for a cold wallet. Or, when Neuron is used as a cold wallet, there should be another protocol to interact with, like Ledger's [Ledger Live](https://support.ledger.com/hc/en-us/articles/8979990022045-How-to-connect-to-NEAR-Wallet-with-your-Ledger-device?docs=true)

This article shows how to connect near account in ledger, do you know if there's an introduction to the protocol?

BTW, here's the protocol of Near for wallet connect: https://docs.walletconnect.com/2.0/advanced/rpc-reference/near-rpc

**Comment by devchenyan** [comment]
IMO,  a new field and a existing method allow wallet authorize dapps to generate addresses

1. allow_address_generation allows users to derive addresses
2. ckb_getAddresses gets the generated addresses（with argument like: generate） when the wallet is offline

The dapp does not know whether the wallet is connected to the node, all that Dapp needs is a set of addresses. So generate_address is unnecessary.
It should be noted that the generated addresses are not continuous and require a certain number limit.

**Comment by Keith-CY** [comment]
> IMO, a new field and a existing method allow wallet authorize dapps to generate addresses
> 
> 1. allow_address_generation allows users to derive addresses
> 2. ckb_getAddresses gets the generated addresses（with argument like: generate） when the wallet is offline
> 
> The dapp does not know whether the wallet is connected to the node, all that Dapp needs is a set of addresses. So generate_address is unnecessary. It should be noted that the generated addresses are not continuous and require a certain number limit.

It seems the same as the rules mentioned at https://github.com/Magickbase/neuron-public-issues/issues/180#issue-1740979681

DApp asks the wallet to generate new addresses with an argument named `generate`, the key problem of this rule that how to prevent dapps from abusing address generation still be there.

**Comment by yanguoyu** [comment]
It seems that for `NEAR Wallet` users can change the path index, it looks the same as giving control to users over whether DApps can derive addresses, but only create an appointed index address.
On the other hand, if we want to ignore the address concept, is it necessary to allow developers to derive addresses with a cold wallet? Maybe we should forbid developers to derive addresses when the wallet is offline.

**Comment by homura** [comment]
The link above I pasted is wrong, here is [how Ledger Live derivates addresses](https://developers.ledger.com/docs/coin/address-derivation/)

**Comment by yanguoyu** [comment]
> The link above I pasted is wrong, here is [how Ledger Live derivates addresses](https://developers.ledger.com/docs/coin/address-derivation/)

[how Ledger Live derivates addresses](https://developers.ledger.com/docs/coin/address-derivation/) only provides SDK to derive addresses, it seems no limit to deriving address.

**Comment by homura** [comment]
> [how Ledger Live derivates addresses](https://developers.ledger.com/docs/coin/address-derivation/) only provides SDK to derive addresses, it seems no limit to deriving address.

What I'm trying to show is that, as a cold wallet, it is stateless, and when developer need to derive addresses, that's when state changes must occur. When we use a BIP-44 like wallet, this derived state needs to be recoverable from the blockchain, i.e., there needs to be an online device to recover this state, rather than keeping the state that needs to be recovered in the cold wallet. 

This link shows the add an **account** instead of a **derived address**, and an account corresponds to a **parent key**, instead of a **child key** corresponding to a specific address

**Comment by devchenyan** [comment]
The core issue now is how to limit the abuse of the ckb_generate_address  by dapp.

There are two situations when the wallet is used offline
1. The user is not aware that the wallet is offline and is still using it
2. The user makes the wallet offline for safety and other considerations

For the first type of user, when the dapp calls ckb_generate_address, the pop-up authorization box can inform the user that the wallet is offline, and the dapp needs to derive addresses. The user can connect the wallet so that the dapp can get the addresses through ckb_getAddresses

For the second type of users, they clearly need the security and privacy of wallet usage. Therefore, each time a dapp requests a derived address, the user can decide whether to allow the corresponding number of addresses to be derived through the number of derived addresses requested by the dapp and the description of the purpose.

```mermaid
sequenceDiagram
    Dapp ->> + Wallet : ckb_generate_address(num, description)
    alt Wallet Online
        Wallet -->> Dapp : Error (wallet online)
    else Wallet Offline
        Wallet ->> + User : request authorization (num + description)
    end
    alt Reject
        User -->> Wallet : User rejected
        Wallet -->> Dapp : Error (user rejected)
    else Approve
        User -->> Wallet : User approved
        Wallet -->> Wallet : generate address
        Wallet -->> Dapp : Result: Address[]
    end
```

**Comment by Keith-CY** [comment]
Updated in https://github.com/Magickbase/neuron-public-issues/issues/148 as `ckb_generateAddresses`
