### ISSUE TITLE
Downplaying the address to strengthen the concept of the account

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#181]
As mentioned in some discussions, we aim to promote an account model in UTXO ecosystem, which is quite different from that in ETH ecosystem.

In ETH ecosystem, an account is mapped to an address, the concept simple and easy to understand.

But in UTXO ecosystem, an account may refer to a bundle of addresses, and the count of addresses is infinite. So it's better to hidden address list from user's view by default.

In our new UI
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/2368ec5d-32c6-48fb-8fa1-11b1a80e6979)

The address list is exposed on the receive page. To dim the detail of address list, it could be collapsed by default and expanded manually for a peek.

How do you think about this UX? @Danie0918 @Sven-TBD

**Comment by Danie0918** [comment]
Enhance the account concept by integrating sending and receiving into the account overview.Here are 2 options:
【Option 1】Integration of send and receive into the overview on existing versions.
1.Send and Receive will be available as 2 options in the overview module, click to initiate the corresponding action.
2.Send will become a secondary page in the overview, and the related actions will remain the same as before.
3.Receive can use pop-ups instead of reducing user actions due to fewer operations.
![new_page_1](https://github.com/Magickbase/neuron-public-issues/assets/122437870/5f1292ad-9c4e-42f0-a679-ef92ae92c969)


【Option 2】By aggregating all wallets together, the account concept will be expanded. Also other modules are needed to provide data for all wallets and provide filtering by wallet.
1.Change the overview to accounts and summarize all wallets.Single wallet send and receive operations are the same as in Scenario 1.
2.History aggregates all wallet transaction history and provides filtering by wallet.
3.The Nervos DAO and Experimental pages provide wallet options to perform operations.
![new_page_2](https://github.com/Magickbase/neuron-public-issues/assets/122437870/ccfa34f0-0c7d-475f-b1d0-414a48e14356)

The changes in Option 1 would be closer to current user habits and with fewer changes. Option 2 changes would make the accounts more integrated, make the category hierarchy clearer, and reduce the cost of use for users.

**Comment by Keith-CY** [comment]
Option 2 is infeasible because light client is up to subscribe 500 scripts. The limit is easy to reach if all wallets are synced simultaneously.

**Comment by Keith-CY** [comment]
> How about giving users two options that include professional and regular? And for professionals we can keep the old design, for regular we can use the new design.
> 
> On the other hand, I guess we do not need to change the send page.

Displaying in professional and normal modes also fits [advance mode on sending transaction](https://github.com/Magickbase/neuron-public-issues/issues/56) we are going to design.

**Comment by Keith-CY** [comment]
Any update on this topic @Danie0918 @Sven-TBD

**Comment by Danie0918** [comment]
Based on the current situation, it is appropriate for us to use Option 1. I don't think it is necessary to split into 2 modes. Option 1 does not change the current functionality, but only modifies the layout to make the overview more holistic and enhance the account concept.I have refined Option 1 below:

【Option 1】Integration of send and receive into the overview on existing versions.
1.Send and Receive will be available as 2 options in the overview module, click to initiate the corresponding action.
2.Send will become a secondary page in the overview, and the related actions will remain the same as before.
3.Receive can use pop-ups instead of reducing user actions due to fewer operations.
-The address book will be moved to the balance of the overview next to the weak display using icons for users who need to click to view it as a pop-up window.
-Receiving does not require user action so it is presented in the form of a pop-up window to reduce page bounces. In addition, for hardware wallets, the previous process is replaced by a change in status of the button and an auxiliary prompt.


![new_page_1](https://github.com/Magickbase/neuron-public-issues/assets/122437870/853ec3dc-182a-4e1e-bb00-2f6a3bfc26c2)

**Comment by Keith-CY** [comment]
> Based on the current situation, it is appropriate for us to use Option 1. I don't think it is necessary to split into 2 modes. Option 1 does not change the current functionality, but only modifies the layout to make the overview more holistic and enhance the account concept.I have refined Option 1 below:
> 
> 【Option 1】Integration of send and receive into the overview on existing versions.
> 
> 1. Send and Receive will be available as 2 options in the overview module, click to initiate the corresponding action.
> 2. Send will become a secondary page in the overview, and the related actions will remain the same as before.
> 3. Receive can use pop-ups instead of reducing user actions due to fewer operations.
>    
>    * The address book will be moved to the balance of the overview next to the weak display using icons for users who need to click to view it as a pop-up window.
>    * Receiving does not require user action so it is presented in the form of a pop-up window to reduce page bounces. In addition, for hardware wallets, the previous process is replaced by a change in status of the button and an auxiliary prompt.
> 
> ![new_page_1](https://user-images.githubusercontent.com/122437870/250344330-853ec3dc-182a-4e1e-bb00-2f6a3bfc26c2.png)

LGTM

**Comment by JeffreyMa597** [comment]
> Based on the current situation, it is appropriate for us to use Option 1. I don't think it is necessary to split into 2 modes. Option 1 does not change the current functionality, but only modifies the layout to make the overview more holistic and enhance the account concept.I have refined Option 1 below:
> 
> 【Option 1】Integration of send and receive into the overview on existing versions.
> 
> 1. Send and Receive will be available as 2 options in the overview module, click to initiate the corresponding action.
> 2. Send will become a secondary page in the overview, and the related actions will remain the same as before.
> 3. Receive can use pop-ups instead of reducing user actions due to fewer operations.
>    
>    * The address book will be moved to the balance of the overview next to the weak display using icons for users who need to click to view it as a pop-up window.
>    * Receiving does not require user action so it is presented in the form of a pop-up window to reduce page bounces. In addition, for hardware wallets, the previous process is replaced by a change in status of the button and an auxiliary prompt.
> 
> ![new_page_1](https://user-images.githubusercontent.com/122437870/250344330-853ec3dc-182a-4e1e-bb00-2f6a3bfc26c2.png)

I have a small question. Where is the entry for the address book? My understanding is that you have removed the navigation 
 sidebar for `receive`, and instead, that can be triggered on the `overview` page. It seems that you can only choose one of these two options, either the receive QR code or the address book.

**Comment by Keith-CY** [comment]
> > Based on the current situation, it is appropriate for us to use Option 1. I don't think it is necessary to split into 2 modes. Option 1 does not change the current functionality, but only modifies the layout to make the overview more holistic and enhance the account concept.I have refined Option 1 below:
> > 【Option 1】Integration of send and receive into the overview on existing versions.
> > 
> > 1. Send and Receive will be available as 2 options in the overview module, click to initiate the corresponding action.
> > 2. Send will become a secondary page in the overview, and the related actions will remain the same as before.
> > 3. Receive can use pop-ups instead of reducing user actions due to fewer operations.
> >    
> >    * The address book will be moved to the balance of the overview next to the weak display using icons for users who need to click to view it as a pop-up window.
> >    * Receiving does not require user action so it is presented in the form of a pop-up window to reduce page bounces. In addition, for hardware wallets, the previous process is replaced by a change in status of the button and an auxiliary prompt.
> > 
> > ![new_page_1](https://user-images.githubusercontent.com/122437870/250344330-853ec3dc-182a-4e1e-bb00-2f6a3bfc26c2.png)
> 
> I have a small question. Where is the entry for the address book? My understanding is that you have removed the navigation sidebar for `receive`, and instead, that can be triggered on the `overview` page. It seems that you can only choose one of these two options, either the receive QR code or the address book.

The entry of address book sits next to the balance
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/070dfacd-2091-4cfb-a0a3-0c43f19bf012)

**Comment by Danie0918** [comment]
In order to avoid too much difference between iteration 4 and the new UI version, we need to complete the overview and receive adjustments in advance of the current version.It contains overview, receive and address book.

**Attention required** : The current UI draft is the one that contains the cell management portal, which does not need to be implemented in this phase.


【Overview】

- Requirement Description
1. Enhance the account concept by integrating sending and receiving into the account overview.
~~2. Allow user to manage cells.~~

![overview](https://github.com/Magickbase/neuron-public-issues/assets/122437870/a4b11d3f-b667-4e4b-a34f-57d2e0215402)


- Requirement Contents
1. Remove the separate levels of send and receive, and adjust the interaction between receive and send in the overview so that it is hierarchically below the overview.（Add Send,Receive under Tool in the top menu bar.）
2. Add Address Book ~~and Cell Management~~ portal located next to the balance.
~~3. Add locked balance display, click to view to go to the Cell Management page.~~


【Receive】

- Requirement Description：Since receive does not involve complex operations, using pop-ups will increase ease of use and reduce page jumps.

![receive](https://github.com/Magickbase/neuron-public-issues/assets/122437870/8e36df40-8506-4732-b09a-892d908e6e68)

- Requirement Contents
[General Wallet]
1. Receive will appear as a pop-up window and apply to the asset account.
2. Retain the original save and download QR code image function, retain the address copy and convert address format function.
3. Move the alert text next to the headline exclamation point and only float it when the user moves into focus.

[Hardware wallet]Replace the previous popup interaction with a button morphology change.
1. When a hardware wallet is used, a Verify Address button is provided.
2. Clicking the Verify button connects the wallet and provides a loading animation.
3. When the connection fails, a retry button is provided and an error message is prompted under the button.
4. Provides an authentication loading animation when the connection is successful, and displays an authentication button when authentication is complete.


【Address Book】

- Requirement Description:Due to the receive  adjustments, the address book as a separate function appears in the form of a pop-up window to show can effectively reduce the page jump to facilitate user operation.

![address_book](https://github.com/Magickbase/neuron-public-issues/assets/122437870/8c3f7371-6562-41c6-a986-8471aeacbdec)

- Requirement Contents
1. Add All/Receiving/Change type categories and show all by default.
2. Retain the original copy address/balance and edit description interactions.
3. Add balance and Txs sorting, click to switch to descending, ascending and restore default sorting status in turn.Click All/Receiving/Change to restore the default sorting.

**Comment by Danie0918** [comment]
UI : [https://github.com/Magickbase/visual-style-guide/issues/31](https://github.com/Magickbase/visual-style-guide/issues/31)

**Comment by Keith-CY** [comment]
> How is it going, is there a package to test? @devchenyan

It's being reviewed at https://github.com/nervosnetwork/neuron/pull/2822 and adding comment `/package` will generate a package for test
