### ISSUE TITLE
Refactor ckb-sdk-utils by lumos

### ISSUE THREAD

**Issue by homura** [Magickbase/neuron-public-issues#201]
https://lumos-website.vercel.app/migrations/migrate-form-ckb-sdk-utils

**Comment by zhangyouxin** [comment]
https://github.com/nervosnetwork/neuron/pull/2734 was closed due to two major reasons:

1. there are too many `isMainnet ? LINA : AGGRON4` expressions in the refator
2. the serialization of `ckb-sdk-util` and `lumos` don't receive the same parameter type of blank value, `utils` uses `null` and `lumos` uses `undefined` for blank value, they are not compatible, so the refator brings complexity by transforming objects that needs to be serilized

For the first problem, we could add a new manager for network switching.

For the second problem, we need to transform `null` to `undefined`,this util can either be provided by `lumos` or implement in `Neuron`. An example:

```ts
// witness args before transform
const witnessArgs = {
  lock: `0x${'00'.repeat(65)}`,
  inputType: null,
  outputType: null,
}

// witness args after transform
const witnessArgs = {
  lock: `0x${'00'.repeat(65)}`,
  inputType: undefined,
  outputType: undefined,
}
```

In that case,  the most certain parts are:

- `scriptToHash(script)` can be replaced with `utils.computeScriptHash(script)`
- `src/models/blake2b.ts` can be replaced with lumos

I think maybe we can implement the certain part first

**Comment by zhangyouxin** [comment]
> You mentioned manager here sound like a stateful?

I was not very sure about this. 
- option 1: It could be a stateful class and exists as a singleton instance in Neuron runtime env, so that the instance can be accessed and provides a `getNetworkType` method.
- option 2: The network type can be persisted in [electron-store](https://github.com/sindresorhus/electron-store)-like data store, and we provide a set of util functions to `CRUD` the current network type

I thouht maybe we can use option 2, and after reading about current code. I find that Neuron is already using option 1:
- https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/controllers/networks/index.ts#L13
- https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/services/networks.ts#L175-L177

So now that I can just utilize this and add a `LumosConfigService` service similar to [network service](https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/services/networks.ts), it is a singleton class providing a `getLumosConfig` public method.

> How many file changes will this refactoring cause?

I think it could be one file, providing util functions to transform `Script`, `WitnessArgs`, `RawTransaction`, `CellDep`, `Transaction`, `OutPoint`, `Block`, `CellInput`, `CellOutput`, `Header`.(need to test all these transformers).
And in real business code, we just need to change `ckb-sdk-utils/serilize(obj)` to `lumos-codec/pack(transform(obj))`

**Comment by homura** [comment]
> So now that I can just utilize this and add a LumosConfigService service similar to [network service](https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/services/networks.ts?rgh-link-date=2023-08-03T03%3A46%3A54Z), it is a singleton class providing a getLumosConfig public method.

A stateful manager may cause other problems, so maybe we can keep the API the same as before

```ts
type scriptToAddress = (script:Script, isMainnet?:boolean) => string;
```

And remove the address conversions that were dependent on the `ckb-sdk-js`

> I think it could be one file

It's LGTM

**Comment by zhangyouxin** [comment]
Prs:

- https://github.com/nervosnetwork/neuron/pull/2801
- https://github.com/nervosnetwork/neuron/pull/2802
- https://github.com/nervosnetwork/neuron/pull/2803

**Comment by yanguoyu** [comment]
The `@nervosnetwork/ckb-sdk-utils` package was not removed from the `UI` package. Will we continue to remove `@nervosnetwork/ckb-sdk-utils`? https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/package.json#L53-L54
