### ISSUE TITLE
Nervos DAO withdraw become deposit

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#210]
When the Nervos DAO withdrawal process suggests a rate change, the transactions deposited to the DAO are generated to overwrite the previous transactions.

![Image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/848e42e0-b11c-4aa5-8fa7-c4f77bf6a704)

**Comment by Danie0918** [comment]
Improved solution: cannot update the transaction when the input password pop-up window opensImproved solution: cannot update the transaction when the input password pop-up window opensImproved solution: cannot update the transaction when the input password pop-up window opens

**Comment by yanguoyu** [comment]
For my suggestion, when the password input dialog is visible, the transaction shouldn't be updated anymore. Then we can ensure that the sending transaction is the same as the user has seen.

**Comment by yanguoyu** [comment]
Currently, `PasswordRequest` will show if the `state.app.passwordRequest.actionType` is not null. So I will add a logic that if the `actionType` is not null, the `UpdateGeneratedTx` will not update tx to another.
But it will have a default logic in this condition, we should update tx at first then we can update actionType. Do you have any suggestions? @Keith-CY @WhiteMinds

https://github.com/nervosnetwork/neuron/blob/a22fb7c5e4f8400bc833f62464d3ac12ff0889a9/packages/neuron-ui/src/states/stateProvider/reducer.ts#L278-L281C1

```typescript
    case AppActions.UpdateGeneratedTx: {
      if (state.app.passwordRequest.actionType !== null) {
            state.app.send.generatedTx = action.payload || null
      }
      break
    }
```

**Comment by WhiteMinds** [comment]
> Currently, `PasswordRequest` will show if the `state.app.passwordRequest.actionType` is not null. So I will add a logic that if the `actionType` is not null, the `UpdateGeneratedTx` will not update tx to another. But it will have a default logic in this condition, we should update tx at first then we can update actionType. Do you have any suggestions? @Keith-CY @WhiteMinds
> 
> https://github.com/nervosnetwork/neuron/blob/a22fb7c5e4f8400bc833f62464d3ac12ff0889a9/packages/neuron-ui/src/states/stateProvider/reducer.ts#L278-L281C1
> 
> ```ts
>     case AppActions.UpdateGeneratedTx: {
>       if (state.app.passwordRequest.actionType !== null) {
>             state.app.send.generatedTx = action.payload || null
>       }
>       break
>     }
> ```

I missed this comment earlier.

This piece of code appears to potentially result in keeping the old transaction (`generatedTx`) instead of the updated transaction that is more aligned with the GUI when `passwordRequest` is canceled. I would not recommend placing this type of business logic in the reducer.

Perhaps the best approach would be to add a new `tx` field to the `passwordRequest` data structure, providing more flexibility.

This way, we can easily compare the latest `generatedTx` with `passwordRequest.tx` and handle any differences automatically.

We can either use `passwordRequest.tx` directly or give the user the option to manually choose between the old and new transactions. For example, after the user confirms their password, we can notify them that the transaction has changed and ask if they want to use the old or new transaction.
