### ISSUE TITLE
Update documents for new UX

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#248]
1. update the present documents of the obsolete UX
2. upload a video of interaction with the new UX
3. // TODO

**Comment by Danie0918** [comment]
【To Do】
1.Release Notes
[Main Tasks]
- New UI
- Bug fix

[Optimizations]
- Optimize input and output storage
- Detect new upgrade on launch
- Optimize the interaction of calendar
- Set synchronization start block

2.New UI Video Introduction
[Chapters]
1.Create & Import Wallets
2.Overview
3.Send&Receive
4.History
5.NervoDAO
6.Settings
7.Experimental
-----------------------------------
8.[Pending]Other Optimizations

3.Update Document Images：[https://docs.nervos.org/docs/basics/guides/crypto%20wallets/neuron/](https://docs.nervos.org/docs/basics/guides/crypto%20wallets/neuron/)
[Provide same name image replacement]

4.Issues Status Updates & PRD.md Updates

**Comment by Danie0918** [comment]
[[Video]](https://github.com/Magickbase/neuron-public-issues/assets/122437870/4fcf4f5d-bd64-4c21-abf9-972d21d629b1)

**Comment by Keith-CY** [comment]
> default.mp4

I have the following suggestions.

1. The logo of Neuorn is incorrect, the one of Magickbase was used. Maybe `Magickbase` can be added as a subtitle with `Powered by [logo] Magickbase`
2. Characters of time table are not aligned
	<img width="528" alt="Pasted Graphic 1" src="https://github.com/Magickbase/neuron-public-issues/assets/7271329/962e68f0-7be6-469f-aa7a-5a629407e028">
3. Captions can be removed, and we can use auto-generated captions of YouTube for better user experience
4. Introduction of `address book` was included in the `receive` part, I think it deserves an independent part because it's not a part of `receive` function
5. Some meaningless hovers on table header appear in `history` part, I think showing interactions such as `copy`, `expand tx detail` is enough.
6. Pronunciation of `DAO` is a bit weird, not sure if it can be optimized.
7. `Custom assets` and `Assets Account` are briefly introduced in `Experimental` part. They deserve their own introduction
	1. `Custom assets`: which assets are expected to be managed here
	2. `Asset Account`: An independent function to manage SUDT assets.

**Comment by silySuper** [comment]
Functions in tools like single sign message/multisig addresses/offine sign which is concluded in new UX do not need to be shown in this video?

**Comment by Danie0918** [comment]
> Functions in tools like single sign message/multisig addresses/offine sign which is concluded in new UX do not need to be shown in this video?

This is mainly a demonstration of the new interface, and has not been adjusted for existing features, so it is not reflected.

**Comment by Danie0918** [comment]
> > default.mp4
> 
> I have the following suggestions.
> 
> 1. The logo of Neuorn is incorrect, the one of Magickbase was used. Maybe `Magickbase` can be added as a subtitle with `Powered by [logo] Magickbase`
> 2. Characters of time table are not aligned
>    <img alt="Pasted Graphic 1" width="528" src="https://user-images.githubusercontent.com/7271329/268577453-962e68f0-7be6-469f-aa7a-5a629407e028.png">
> 3. Captions can be removed, and we can use auto-generated captions of YouTube for better user experience
> 4. Introduction of `Address book` was included in the `Receive` part, I think it deserves an independent part because it's not a part of `Receive` function
> 5. Some meaningless hovers on table header appear in `History` part, I think showing interactions such as `copy`, `expand tx detail` is enough.
> 6. Pronunciation of `DAO` is a bit weird, not sure if it can be optimized.
> 7. `Custom assets` and `Assets Account` are briefly introduced in `Experimental` part. They deserve their own introduction
>    
>    1. `Custom Assets`: which assets are expected to be managed here
>    2. `Asset Account`: an independent function to manage SUDT assets.


https://github.com/Magickbase/neuron-public-issues/assets/122437870/22da51e0-9ff6-45ec-aa13-4f25996de4f5

**Comment by Danie0918** [comment]
Update description text, here the download bit order has been adjusted so that users can find the download package faster.

---

# 0.110.3 (2023-XX-XX)

**Major Changes**：After careful improvement, we bring you a new user experience and easier interaction.

**Completely Updated UI**: We completely redesigned the software's user interface, working to provide a more aesthetically pleasing, intuitive and modern look. The new UI has been carefully optimized to enhance user experience and operational efficiency. You will find that the new interface has a clearer layout, more distinctive colors and icons, and an overall style that is more in line with the times. We are confident that the new user interface will bring you a pleasant and comfortable experience.

**Updated Interaction**: Focusing on the pain points and troubles encountered by users in the process of using the software, we have improved the interaction in a targeted way, making it easier and more intuitive to use the software. Instead of struggling to find functions and options, the new version of the software name optimizes the menu structure and navigation so that you can find what you need more quickly. Our goal is to make your operations more efficient and enjoyable.

In addition to these two points, we have made a number of other improvements and optimizations to enhance the overall user experience. We've heard your feedback and suggestions and have incorporated them into the new version in the hope that we can meet more of your expectations.


### Downloads


---


## New features

- [#77](https://github.com/Magickbase/neuron-public-issues/issues/77): Optimize input and output storage(@yanguoyu)
- [#139](https://github.com/Magickbase/neuron-public-issues/issues/139): Detect new upgrade on launch(@yanguoyu)
- [#151](https://github.com/Magickbase/neuron-public-issues/issues/151): Optimize the interaction of calendar(@WhiteMinds)
- [#181](https://github.com/Magickbase/neuron-public-issues/issues/181): Downplaying the address to strengthen the concept of the account(@devchenyan)
- [#183](https://github.com/Magickbase/neuron-public-issues/issues/183): Specify start point to sync when a wallet is imported and synced in light-client mode(@yanguoyu)
- [#200](https://github.com/Magickbase/neuron-public-issues/issues/200): Rename the built-in CKB node(@yanguoyu)
- [#252](https://github.com/Magickbase/neuron-public-issues/issues/252): Supporting Spore(@homura)


## Bug fixes and optimizations 

- [#172](https://github.com/Magickbase/neuron-public-issues/issues/172): In Nervos DAO, when there is a decimal when choosing to deposit in CKB, keep 8 digits(@WhiteMinds)
- [#178](https://github.com/Magickbase/neuron-public-issues/issues/178): Unable to detect hardware wallet(@yanguoyu)
- [#184](https://github.com/Magickbase/neuron-public-issues/issues/184): After send sudt the sync process will stop with light client(@yanguoyu)
- [#209](https://github.com/Magickbase/neuron-public-issues/issues/209): The 102 CKB deposit check can be walkaround if you double click the checkbox(@yanguoyu)
- [#210](https://github.com/Magickbase/neuron-public-issues/issues/210): Nervos DAO withdraw become deposit(@yanguoyu)
- [#216](https://github.com/Magickbase/neuron-public-issues/issues/216): Deposit all doesn't work when the fee rate is updated(@yanguoyu)
- [#221](https://github.com/Magickbase/neuron-public-issues/issues/221): Offline sign not shown error message if broadcast error(@devchenyan)
- [#241](https://github.com/Magickbase/neuron-public-issues/issues/241): Nervos Dao deposit balance move to max,pop up deposit window will disappear(@yanguoyu)
- [#254](https://github.com/Magickbase/neuron-public-issues/issues/254): Add service for compatibility between Neuron and CKB node/client(@yanguoyu)

**Comment by Keith-CY** [comment]
> Update description text, here the download bit order has been adjusted so that users can find the download package faster.
> 
> # 0.110.3 (2023-XX-XX)
> **Major Changes**：After careful improvement, we bring you a new user experience and easier interaction.
> 
> **Completely Updated UI**: We completely redesigned the software's user interface, working to provide a more aesthetically pleasing, intuitive and modern look. The new UI has been carefully optimized to enhance user experience and operational efficiency. You will find that the new interface has a clearer layout, more distinctive colors and icons, and an overall style that is more in line with the times. We are confident that the new user interface will bring you a pleasant and comfortable experience.
> 
> **Updated Interaction**: Focusing on the pain points and troubles encountered by users in the process of using the software, we have improved the interaction in a targeted way, making it easier and more intuitive to use the software. Instead of struggling to find functions and options, the new version of the software name optimizes the menu structure and navigation so that you can find what you need more quickly. Our goal is to make your operations more efficient and enjoyable.
> 
> In addition to these two points, we have made a number of other improvements and optimizations to enhance the overall user experience. We've heard your feedback and suggestions and have incorporated them into the new version in the hope that we can meet more of your expectations.
> 
> ## Downloads
> ## New features
> * [#77](https://github.com/Magickbase/neuron-public-issues/issues/77): Optimize input and output storage(@yanguoyu)
> * [#139](https://github.com/Magickbase/neuron-public-issues/issues/139): Detect new upgrade on launch(@yanguoyu)
> * [#151](https://github.com/Magickbase/neuron-public-issues/issues/151): Optimize the interaction of calendar(@WhiteMinds)
> * [#181](https://github.com/Magickbase/neuron-public-issues/issues/181): Downplaying the address to strengthen the concept of the account(@devchenyan)
> * [#183](https://github.com/Magickbase/neuron-public-issues/issues/183): Specify start point to sync when a wallet is imported and synced in light-client mode(@yanguoyu)
> * [#200](https://github.com/Magickbase/neuron-public-issues/issues/200): Rename the built-in CKB node(@yanguoyu)
> * [#252](https://github.com/Magickbase/neuron-public-issues/issues/252): Supporting Spore(@homura)
> 
> ## Bug fixes and optimizations
> * [#172](https://github.com/Magickbase/neuron-public-issues/issues/172): In Nervos DAO, when there is a decimal when choosing to deposit in CKB, keep 8 digits(@WhiteMinds)
> * [#178](https://github.com/Magickbase/neuron-public-issues/issues/178): Unable to detect hardware wallet(@yanguoyu)
> * [#184](https://github.com/Magickbase/neuron-public-issues/issues/184): After send sudt the sync process will stop with light client(@yanguoyu)
> * [#209](https://github.com/Magickbase/neuron-public-issues/issues/209): The 102 CKB deposit check can be walkaround if you double click the checkbox(@yanguoyu)
> * [#210](https://github.com/Magickbase/neuron-public-issues/issues/210): Nervos DAO withdraw become deposit(@yanguoyu)
> * [#216](https://github.com/Magickbase/neuron-public-issues/issues/216): Deposit all doesn't work when the fee rate is updated(@yanguoyu)
> * [#221](https://github.com/Magickbase/neuron-public-issues/issues/221): Offline sign not shown error message if broadcast error(@devchenyan)
> * [#241](https://github.com/Magickbase/neuron-public-issues/issues/241): Nervos Dao deposit balance move to max,pop up deposit window will disappear(@yanguoyu)
> * [#254](https://github.com/Magickbase/neuron-public-issues/issues/254): Add service for compatibility between Neuron and CKB node/client(@yanguoyu)

It's cool, but PRs could be re-organized because some of them are intended to fix issues that came from new UI implementation, not those in last release.

I've a list of PRs at https://github.com/nervosnetwork/neuron/pull/2845#issue-1904116071
