### ISSUE TITLE
Add script to update weekly progress

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#338]
Automatically synchronize weekly project progress to the PM channel on discord using a script.

Project：
[[Neuron]](https://github.com/orgs/Magickbase/projects/6) 
[[CKB Explorer]](https://github.com/orgs/Magickbase/projects/9)

Contents:Issue title and links
1. New for this week
2. In Progress (Show Scheduled)
3. Code Review/Testing (Show by status)
4. Completed this week (Show by status)

**Comment by Danie0918** [comment]
Support RSS.

**Comment by WhiteMinds** [comment]
I think we can create a new repository, possibly called 'Weekly Reports' or something similar.

In this repository, we can set up GitHub Actions to take a complete snapshot of the current board data at a specific time each week (e.g., weekends). Once the snapshot is obtained, an automated PR can be created and submitted to this repository itself. The relevant stakeholders can review and make corrections before merging.

Additionally, there will be other GitHub Actions responsible for detecting changes in the snapshots. Based on the latest and previous snapshots, these actions can automatically generate the current weekly report data to be displayed. Another automated PR can be created and submitted to this repository, allowing the relevant stakeholders to review and make corrections before merging.

This repository will also include a backend component (possibly implemented using Vercel + Next.js) that exposes the current weekly report data through various response formats such as JSON and RSS.

The advantage of this approach is that it provides a space for manual intervention through PRs, allowing for content review and corrections. Moreover, it is a separate repository, ensuring complete isolation of the weekly report functionality from other projects.

@Keith-CY What do you think?

**Comment by Keith-CY** [comment]
> The advantage of this approach is that it provides a space for manual intervention through PRs, allowing for content review and corrections. Moreover, it is a separate repository, ensuring complete isolation of the weekly report functionality from other projects.
> 
> @Keith-CY What do you think?

Keep it simple, fetching the latest status of various kanbans and generating a report in the website repo requires less code and fewer steps.

Manual intervention can be introduced by submitting automated PR in https://github.com/Magickbase/websites, and isolation of content is unnecessary because https://github.com/Magickbase/websites is a repo of content(branding, projects, team, vision, etc.), the generated reports could be considered as a part of it.

**Comment by WhiteMinds** [comment]
> Keep it simple, fetching the latest status of various kanbans and generating a report in the website repo requires less code and fewer steps.

Without (at least one) historical snapshot, it is not possible to obtain a weekly **change** report. Instead, it will be a complete snapshot of the board.

> Manual intervention can be introduced by submitting automated PR in https://github.com/Magickbase/websites, and isolation of content is unnecessary because https://github.com/Magickbase/websites is a repo of content(branding, projects, team, vision, etc.), the generated reports could be considered as a part of it.

Sure, I initially thought that this data might be used in multiple places in the future. However, now it seems that regardless of whether it is used in multiple places, we can consider it as a service under the `websites`.

**Comment by Keith-CY** [comment]
> Without (at least one) historical snapshot, it is not possible to obtain a weekly change report. Instead, it will be a complete snapshot of the board.

There are 3 solutions to generate a weekly report:
1. query issues with `since` parameter(https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues) to get issues updated in the past 2 weeks;
2. each issue has `start processing date` and `actual done date`, which can be used in the filter

After getting target issues, weekly report can be generated with their `status`(planning, ..., done)

The 3rd solution is to compare two complete reports to get a diff as the weekly report, e.g.

Report 1
```
[Done] issue_a
[Done] issue_b
[Test] issue_c
[Review] issue_d
[Planning] issue_e
```

Report 2
```
[Done] issue_c
[Test] issue_d
[Review] issue_e
[Planning] issue_f
```

Get diff as the weekly report

- ~~[Test]~~[Done] issue_c
- ~~[Review]~~[Test] issue_d
- ~~[Planning]~~[Review] issue_d
- [Planning] issue_f

**Comment by WhiteMinds** [comment]
All three options sound feasible, but I am still planning to use the third option because it reduces reliance on manual workflows (updating issues, setting dates, etc.).

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/websites/pull/58
